#include "payout_info.xpm"
#include "icon.xpm"

#include "draw_card.xpm"
#include "draw_card_pressed.xpm"

#include "1.xpm"
#include "2.xpm"
#include "3.xpm"
#include "4.xpm"
#include "5.xpm"
#include "6.xpm"
#include "7.xpm"
#include "8.xpm"
#include "9.xpm"
#include "10.xpm"
#include "11.xpm"
#include "12.xpm"
#include "13.xpm"
#include "14.xpm"
#include "15.xpm"
#include "16.xpm"
#include "17.xpm"
#include "18.xpm"
#include "19.xpm"
#include "20.xpm"
#include "21.xpm"
#include "22.xpm"
#include "23.xpm"
#include "24.xpm"
#include "col_1-2.xpm"
#include "col_3-4.xpm"
#include "col_1.xpm"
#include "col_2.xpm"
#include "col_3.xpm"
#include "col_4.xpm"
#include "row_1-2.xpm"
#include "row_3-4.xpm"
#include "row_5-6.xpm"
#include "row_1.xpm"
#include "row_2.xpm"
#include "row_3.xpm"
#include "row_4.xpm"
#include "row_5.xpm"
#include "row_6.xpm"

#include "1_pressed.xpm"
#include "2_pressed.xpm"
#include "3_pressed.xpm"
#include "4_pressed.xpm"
#include "5_pressed.xpm"
#include "6_pressed.xpm"
#include "7_pressed.xpm"
#include "8_pressed.xpm"
#include "9_pressed.xpm"
#include "10_pressed.xpm"
// #include "11.xpm"
// #include "12.xpm"
// #include "13.xpm"
// #include "14.xpm"
// #include "15.xpm"
// #include "16.xpm"
// #include "17.xpm"
// #include "18.xpm"
// #include "19.xpm"
// #include "20.xpm"
// #include "21.xpm"
// #include "22.xpm"
// #include "23.xpm"
// #include "24.xpm"
#include "col_1-2_pressed.xpm"
#include "col_3-4_pressed.xpm"
#include "col_1_pressed.xpm"
#include "col_2_pressed.xpm"
#include "col_3_pressed.xpm"
#include "col_4_pressed.xpm"
// #include "row_1-2.xpm"
// #include "row_3-4.xpm"
// #include "row_5-6.xpm"
// #include "row_1.xpm"
// #include "row_2.xpm"
// #include "row_3.xpm"
// #include "row_4.xpm"
// #include "row_5.xpm"
// #include "row_6.xpm"

#include "card_blank.xpm"
#include "card_1.xpm"
#include "card_2.xpm"
#include "card_3.xpm"
#include "card_4.xpm"
#include "card_5.xpm"
#include "card_6.xpm"
#include "card_7.xpm"
#include "card_8.xpm"
#include "card_9.xpm"
#include "card_10.xpm"
#include "card_11.xpm"
#include "card_12.xpm"
#include "card_13.xpm"
#include "card_14.xpm"
#include "card_15.xpm"
#include "card_16.xpm"
#include "card_17.xpm"
#include "card_18.xpm"
#include "card_19.xpm"
#include "card_20.xpm"
#include "card_21.xpm"
#include "card_22.xpm"
#include "card_23.xpm"
#include "card_24.xpm"